server:
  port: 8500
spring:
  application:
    name: fixed-loss-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: thw
    password: thw19971017thw
    url: jdbc:mysql://47.52.128.159:3306/insuranceDB
    tomcat:
      max-wait: 10000
      min-idle: 20
      max-idle: 100
      max-active: 300
  redis:
    host: 192.168.67.128
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 10
        max-wait: 10000
  activiti:
    database-schema: update
    check-process-definitions: false
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    encoding: UTF-8
eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: Mapper/*Mapper.xml
  type-aliases-package: java.util

